### ISSUE TITLE
[Enhancement] In SageTV "Guide", vertical scroll bar is hard to control

### ISSUE THREAD

**Issue by FoggySageTV** [OpenSageTV/sagetv-miniclient#11]

**Comment by FoggySageTV** [comment]
When I have the SageTV Guide page open, I am having trouble scrolling up or down through the different channels.  Double tapping on the vertical scroll bar ends causes the scroll bar to roll rapidly until I tap on the vertical scroll bar again, which makes it hard to see the guide and to select a channel to watch.  It acts like a double tap on the scroll bar ends tells the SageTV app that something is holding down the scroll bar end.
Would it be possible to either just issue one page up/down event when the ends of the scroll bar are doubled tapped or to add a vertical swipe in the vertical scroll bar location to issue a page up/down event?
Note: trying to tap on the scroll bar is a pain as SageTV thinks I just tapped on a show next to the scroll bar.

**Comment by stuckless** [comment]
Have you tried using a two finger swipe up/down for page up/page down?

I agree that the UI, as is, especially scrollbars, are hard to use on a phone UI.  Unfortunately, the app has no idea if you touch a scrollbar, button, or empty space, all it can do it pass that information to sagetv for processing.  I have no idea if you on the main menu, settings, guide, etc.

**Comment by stuckless** [comment]
Nothing we can do about this on phone/tablet UIs.
