### ISSUE TITLE
[Enhancement] Remap Android TV home button to Sage home

### ISSUE THREAD

**Issue by brewston** [OpenSageTV/sagetv-miniclient#15]
Attempting to keep the user within miniclient (Until they exit via the STV's exit menu option) may be preferable to having to stop video then resume etc. Just need to be careful not to trap the user inside miniclient should it be hung, maybe a long press on home can return to launcher ?

**Comment by stuckless** [comment]
Maybe a better alternative would be to allow for a "mapping" screen inside the application so that for any given button a user can choose to map a long press and single press action.  (prevent re-mapping of up/down/left/right/select single press actions)

**Comment by brewston** [comment]
That would work too. Can you differentiate between whether video is playing or not ? For example, mapping right direction to FF when video is playing, but used for menu navigation otherwise ?

**Comment by stuckless** [comment]
Unfortunately, that won't be possible.  I already tried this, and I ran into a few issues.  for example, when a video is playing and THEN sagetv thows up a dialog (options menu), I have no Idea that SageTV is doing that, and so, the "navigation" keys are still in video mode, but you need to interact with the UI.  So, doing this is not possible, today, without also doing some changes in the server code.

**Comment by stuckless** [comment]
After some research, it would appear that you cannot "hook" into the HOME button.  This is by design to prevent apps from putting you in app jail.  I guess we are stuck with HOME existing the app.

**Comment by brewston** [comment]
Makes sense, thanks for looking in to it :)
