### ISSUE TITLE
Add buffering to the PULL datasource

### ISSUE THREAD

**Issue by stuckless** [OpenSageTV/sagetv-miniclient#21]

**Comment by brewston** [comment]
Would it be possible to get more detail on how PULL is going to work ? At the moment, when I enable PULL I can FF through recorded TV (Hooray!) but (as warned in preferences) it breaks Live TV. Will this functionality fix Live TV ? Thanks

**Comment by stuckless** [comment]
No, the ONLY way we are getting LiveTV is by using PUSH (which is works now -- but we can't FF/REW)

**Comment by brewston** [comment]
OK, I got it wrong :)

**Comment by stuckless** [comment]
Pull DataSource has a small buffer (required for ExoPlayer)
