### ISSUE TITLE
ExoPlayer: Seeking while paused jumps to beginning of file and throws off audio/video sync

### ISSUE THREAD

**Issue by cncb-gh** [OpenSageTV/sagetv-miniclient#29]
If you seek while paused, the playback position jumps to the beginning of the file and the audio/video sync is off until you restart playback.  It would be ideal if it would seek and then update the (static) image with the current location while staying paused.

**Comment by jvl711** [comment]
This should be fixed in v1.6.3.  If this is not fixed let me know.
