### ISSUE TITLE
[Enhancement] Add usage instructions on the main page

### ISSUE THREAD

**Issue by FoggySageTV** [OpenSageTV/sagetv-miniclient#34]
Suggestion - add usage instructions (swipes, long touch, etc...) to a link on the miniclient front page.

**Comment by stuckless** [comment]
Just to clarify... do you mean the main page on the forums, or the github first page (readme)?  It is on the forums.

**Comment by FoggySageTV** [comment]
On the main page of the MiniClient itself, so that the MiniCLient contains the gesture instructions.

I was envisioning a link under the Server(s) that says something like "Gesture Instructions".  When that is "clicked", opens a page or popup that lists the gestures / instructions to use with the MiniClient.

**Comment by stuckless** [comment]
Gotcha... Good idea.

**Comment by stuckless** [comment]
In the latest beta.
