### ISSUE TITLE
Add a preference to exit the app when exiting sage

### ISSUE THREAD

**Issue by pforemanpf** [OpenSageTV/sagetv-miniclient#38]
When exiting SageTV from client mode, the default behavior is to take you back to the server selection page.  It would be nice to have a preference that would allow you to exit the app completely when SageTV is exited.

**Comment by stuckless** [comment]
There is a preference to exit to the home screen when exiting sagetv in BETA9

**Comment by pforemanpf** [comment]
Awesome, thanks!  I will try this version as soon as it is cut.  Thank you so much for adding this, the WAF is about to go up dramatically! :)
