### ISSUE TITLE
Placeshifter streaming options improvements

### ISSUE THREAD

**Issue by Jabroni** [OpenSageTV/sagetv-miniclient#39]
Currently the Windows version of the placeshifter allows us to change some streaming options which might be useful to tweak under some situations. The current options presented are:
- Use SageTV Dynamic Streaming System (which I suppose as its currently implemented)
- Playback media without transcoding
- Manually specify the encoding parameters 
  - Video Bitrate (kbps)
  - Video resolution
  - Video Frames per Second
  - Key Frames Interval (seconds)
  - Use B-Frames in video encoding
  - Audio Bitrate (kbps)

Maybe on the manual encoding parameters offer some presets, like 512kbps 480p, 2mbit 720p etc (and those profiles would just fill the appropriate settings for encoding parameters)

And having that set, it would be useful to show somewhere what bitrate a video is playing back

**Comment by jvl711** [comment]
@Jabroni 

These changes are slated for the next release.

Josh

**Comment by jvl711** [comment]
This was added in the last version.  I am going to close this issue.
