### ISSUE TITLE
Audio playback continues at Android TV launcher

### ISSUE THREAD

**Issue by brewston** [OpenSageTV/sagetv-miniclient#4]
When I play back a video and press the 'home' button on the Android TV remote, the audio continues playing in the background and continues to play even over other apps (Tested youtube & Plex) on returning to minclient, audio continues but video does not return

**Comment by stuckless** [comment]
Leaving the app (ie, pausing it) will now stop the media player.

**Comment by brewston** [comment]
Should this change be in code on github ? I cloned & built it yesterday and still have this problem

**Comment by stuckless** [comment]
Yeah, it's fixed in ALPHA-7... so likely not on github yet...
