### ISSUE TITLE
[Enhancement] Add more button mappings (nVidia gamepad)

### ISSUE THREAD

**Issue by kfstein** [OpenSageTV/sagetv-miniclient#41]
I would like to see more hardcoded button mappings for the nVidia SHIELD gamepad until a more flexible button mapping system is available.  For example:
- Right stick up/down = Channel (page) up/down
- Right stick right/left = Chapter next/prev
- Right bumper = Delete
- Right trigger = Home

Those are the main buttons I'm missing, but could also use say right/left stick buttons set to guide/info.

It doesn't matter to me what the hardcoded mappings are, but these eamples seemed to follow the current directional pad/sticks doing navigation and buttons/triggers doing actions.

**Comment by stuckless** [comment]
I looked into this... mapping buttons bumpers (or A,B,X,Y) or anything that "clicks" can be done... the other other things are analog controls, and they can also be mapped, but that's going to be much harder to do, since they are not on/off buttons, but rather they shoot intensity values based on how much of the control is being moved.

**Comment by kfstein** [comment]
Forget the analog sticks then, (although now the left stick seems to work the same as the DPad). It sounds like the nVidia remote registers short and log presses. The controller does not, although a Harmony remote does. If you long press right/left/up/down on the controller (DPad or left stick) it registers the same as a short press as soon as you release. I am looking to register something like page up/down and skip right/left over commercials on the controller. A long press is fine if it worked. Also add some buttons on the controller to do things that I use a bit i.e. Delete and Home and Previous Channel.

**Comment by stuckless** [comment]
Gamepad buttons can be mapped in the media keys settings
