### ISSUE TITLE
Full-Screen On Screen Navigation

### ISSUE THREAD

**Issue by kfstein** [OpenSageTV/sagetv-miniclient#42]
An option to have a full-screen on screen navigation screen would be nice.  The buttons on the L-shaped layout can be too small to press effectively.  Maybe a stripped-down selection for navigation/playback options with current-sized icons enclosed in a larger circle outline overlaid on the screen with everything transparent except the icon and circle outline.  Press anywhere in the (larger) circle area to perform the action.

Maybe also a swipe-left action WHEN the on-screen navigation is open to close it, (mirroring the swipe-right to open it), instead of having to press the "eye" icon.

**Comment by jvl711** [comment]
This item is on my personal list of enhancements.  I would like to make phone usage a lot better.

**Comment by jvl711** [comment]
Initial development is complete on this.  In testing.
