### ISSUE TITLE
SageTV 1.0-RC4 client does not register as an installed android app (firetv)

### ISSUE THREAD

**Issue by pforemanpf** [OpenSageTV/sagetv-miniclient#44]
When installing the 1.0-RC4 client, it does not appear on the list of installed applications that can be managed by android.  It will show up in the firetv launcher but if I go to application management the client is not listed and I can not uninstall, or clear data or cache like I can with other applications.  The application appears to run as expected when launched but the only way to uninstall this version is to use adb commands to remove the sagex.miniclient package.

This is not present in the 1.0-RC2 or earlier builds.  This is on FireOS 5.0.5 (Android 5.1 fork) on first and second gen FireTVs.

**Comment by jvl711** [comment]
Closing this issue since we have a Amazon app store entry.  I am not sure if there is a way to do this without using the app store.

Josh
