### ISSUE TITLE
Client hangs after user/pass screen - eventually exits.

### ISSUE THREAD

**Issue by mhassman** [OpenSageTV/sagetv-miniclient#49]
Hi, I'm unable to try rc5 - app icon is missing after install (non-rooted verizon samsung galaxy s5).. but on rc2, I can get to the login screen, enter user/pass via onscreen keyboard, but nothing happens after pressing the login button. debug log attached.
[sagetv-miniclient.txt](https://github.com/OpenSageTV/sagetv-miniclient/files/175593/sagetv-miniclient.txt)

For reference, the original sagetv placeshifter works fine from this same network.

**Comment by stuckless** [comment]
I think you'll need to check the server logs to see what is happening as well... From the client log it looks like there is a problem in the Crypto layer... but no-one else has actually complained about this, so, it's likely something specific with your hardware.

**Comment by mhassman** [comment]
I tried again with v1.0.1 - same issue. 
Server log attached. It looks as though encryption is negotiated successfully - makes it to loading the stvi's.

[server-log.txt](https://github.com/OpenSageTV/sagetv-miniclient/files/203146/server-log.txt)

**Comment by stuckless** [comment]
@mhassman  - What is the sagetv server version?  (It shouldn't matter, but just curious).   I know people do use the Placeshifter feature of the MiniClient, today, so, in general it does work.  Not sure what is the issue in your env that would cause it to hang.

If you want, I can try to connect remotely to your sagetv server (you'd have to set up a user for me) and then I can hook up the app to the debugger while it is connecting to see what is happening in the client.  If you go this route, just PM me the details on the SageTV forum.

**Comment by mhassman** [comment]
SageTV v7.1.9.256 - last one before google bought them. I'll follow up with a PM on the forum. Thnx!

**Comment by mhassman** [comment]
Embarrassing answer.. when using the slide-out on-screen keyboard, double-tap (instead of single-tap) the login button.
Thnx Stuckless!
:-)
