### ISSUE TITLE
In-Sage volume controls not implemented with ijkplayer

### ISSUE THREAD

**Issue by CraziFuzzy** [OpenSageTV/sagetv-miniclient#5]
Toying around with using the web ui for full featured remote capabilities, and I noticed the sage volume controls are not functioning.  Not of immediate need, just figured it should be tracked.

**Comment by stuckless** [comment]
I haven't implemented the "SET_VOLUME" command, yet (along with a few others).  But, good to track it.  Thanks.

**Comment by jvl711** [comment]
I am not sure if I am misunderstanding this or not.  I think that the volume controls are properly implemented in the current version.  Let me know if I am incorrect.
