### ISSUE TITLE
"Non Standard" External Port Support

### ISSUE THREAD

**Issue by jason-bean** [OpenSageTV/sagetv-miniclient#51]
The Android miniclient doesn't seem to support connecting to ports other than 31099. I've recently had to change the external port to our Placeshifter due to blocking at work. On the guest wifi they block higher port numbers. I've also had to move Plex to a lower port.

I know the response from the locator server provides not only the IP address but also the port. Should be a fairly simple matter to use it.

**Comment by stuckless** [comment]
I looked at the code, and I think this is a case whereby I'm actually dropping the port when I persist (and then load) the Server Info (ie, a bug).
