### ISSUE TITLE
ExoPlayer: seeking with comskip skips to the end of a recording

### ISSUE THREAD

**Issue by jrmull** [OpenSageTV/sagetv-miniclient#55]
The watched status and 'resume' vs 'start from beginning' doesn't seem to change the behavior.  In any case, playback skips to the end of the file.

Client: Nvidia Shield Android TV SW v 3.1 (24.5.78.96) 
MiniClient v: 1.0.4

**Comment by stuckless** [comment]
What is the filetype for this... .ps, .ts, mkv, etc.  Different file formats are processed differently, so trying to narrow this down.

**Comment by jrmull** [comment]
.ts format.  I filed this bug after noticing it on a 1080i MPEG2 rerecording from HDHR cable card.  OpenDCT network encoder using FFmpeg muxer.

I can attempt to reproduce and get a sample file if that'd help.
