### ISSUE TITLE
Leanback banner is missing

### ISSUE THREAD

**Issue by brewston** [OpenSageTV/sagetv-miniclient#6]
You could use the banner from Phoenix-app-ng, I already have it in my clone.

**Comment by stuckless** [comment]
You should create a pull request ;)   It' is on my list... just hasn't reached the top, yet.

**Comment by brewston** [comment]
Still trying to get my head around github :) does a pull fork your code then ? can i just push my changes ? I assume you get to approve them ? ;)

**Comment by stuckless** [comment]
You'd need to fork my repo... and then you can push to your repo and submit a pull request into my repo.  Don't worry if you don't know how... I'll try to pull in the icon, later.  Ideally, I'd like someone to create a new icon, though.

**Comment by brewston** [comment]
Forking the repo seemed overkill for such a small change :) Build 8 has the banner, so closing
