### ISSUE TITLE
Aspect Ratio

### ISSUE THREAD

**Issue by mlcarson** [OpenSageTV/sagetv-miniclient#62]
The SageTV command 96 does not control aspect ratio on the MiniClient.  The only way to do this appears to be via an onscreen button but this onscreen menu is only accessible via an extended button press of the Select Key which makes it inaccessible from anybody exclusively using a FLIRC with a normal TV remote. There should be a keystroke which can also access this setting or to access the soft button menu.  It would be nice if the keystroke mapped would be via whatever was mapped in Sage Command 96 (Aspect Ratio toggle).

The default aspect ratio for 4:3 content appears to be AR Fill which distorts the picture on a 16:9 screen.  Vertical black bars on each side would be preferable to maintain the true aspect ratio of the content.  If the aspect ratio toggle can be fixed so that it's accessible from a normal remote then this is less of an issue.

**Comment by stuckless** [comment]
Fixed
