### ISSUE TITLE
Seeking during media playback doesn't work in Live TV

### ISSUE THREAD

**Issue by bialio** [OpenSageTV/sagetv-miniclient#65]
I've noticed this consistently in the following scenario:

Watching live TV, when a show ends and a new show starts, seeking on the new show doesn't work.  When I try to jump backwards, it stays in the same spot.

I notice this usually on sports, when I tune to the channel prior to the start of the show for the pre-game show.  So it's likely on just my HDHR recordings (MPEG2 1080i).

**Comment by stuckless** [comment]
It's interesting, because the MiniClient doesn't have any concept of LiveTV vs Recorded TV.... In both cases, the server just sends the Client buffers of video.

Can you confirm that HD300 behaves differently... it's possible that SageTV is sending me some hint and I'm not processing it.

**Comment by bialio** [comment]
I finally got around to this scenario on the HD300 - it doesn't happen there. 

btl.

**Comment by jvl711** [comment]
@bialio 

This might be fixed with the enhancements in v1.6.3.  Would you mind retesting and confirming.

Josh

**Comment by bialio** [comment]
I don't have any Sage servers running at the moment, so won't be able to test.  Sorry!
