### ISSUE TITLE
FireTV Keyboard Issues with MiniClient Placeshifter Locator / Login

### ISSUE THREAD

**Issue by JazzTech** [OpenSageTV/sagetv-miniclient#66]
My SageTV Server has a user/login implemtented when using a Placeshifter.

I have the SageTV Miniclient v1.2.4 installed on my FireTV (2015) box.

When I add a new SageTV server with my Placeshifter Locator ID, I am prompted for the new server name and Locator ID. This works fine, and I can enter the server name/Locator ID using my connected Bluetooth Keyboard.

After I try to connect to the new SageTV server, I am immediately sent to the SageTV Login page, which wants the SageTV User Name / Password. This is where the problem occurs (100% repeatable). At this point the FireTV virtual keyboard automatically pops up, but I can't easily enter my SageTV user name/password, or access the various buttons/checkboxes on the screen. The Miniclient is unusable after this.

A more significant failure is that the FireTV virtual keyboard is trapped on the screen permanently after this point and can't be removed unless the FireTV box is reset by pulling the power. (Leaving the MiniClient application - which is difficult - has no effect on the FireTV virtual keyboard).

**Comment by wellthen01** [comment]
The problem with the keyboard getting stuck is not limited to providing a Locator ID. I have a new 4K FireTV purchased during the holidays. I was using the keyboard to enter channel numbers in the guide, and found myself stuck with the keyboard over the top of the Sage app and no apparent way to exit the keyboard. Even after using the home key on the FireTV remote to get back to FireTV home, the keyboard still was on top. I will probably have to reboot as JazzTech did.

**Comment by jimbgroves** [comment]
Did anyone ever figure this out?  I am having the same problem.

**Comment by jvl711** [comment]
I Believe this issue is fixed.  Please let me know if it is not and I will reopen.

Josh
