### ISSUE TITLE
After video playback, last video frame is still visible under the menus

### ISSUE THREAD

**Issue by stuckless** [OpenSageTV/sagetv-miniclient#7]

**Comment by brewston** [comment]
I'd noticed this too

**Comment by stuckless** [comment]
Will be fixed in ALPHA-16

**Comment by brewston** [comment]
Confirmed fixed here too in build 16

**Comment by jrmull** [comment]
I think that there may be a regression for this issue in the first beta build.  I could try to get a screenshot if no one else is seeing it.

**Comment by stuckless** [comment]
If you are using ExoPlayer, then I do think you will still see the ghosting image.  But in IJKPlayer it is fixed.  (or should be)
