### ISSUE TITLE
Password input wont bring up Android keyboard

### ISSUE THREAD

**Issue by Jabroni** [OpenSageTV/sagetv-miniclient#70]
When doing Placeshifting on a remote network (whenever Sage will ask for Username and password), when clicking on the password text field it wont bring the keyboard to input password. Happens on Android Mobile and AndroidTV. On the username textbox it does bring up the android keyboard for input.

So far the only way to input the text is with an external keyboard (like bluetooth or usb).

**Comment by jvl711** [comment]
@Jabroni 

I am going to called this fixed :).  I know the fix is a bit of a hack, but it is the best solution I have for right now.  The keyboard should pop when on the password screen/

Josh
