### ISSUE TITLE
Add additional androidTV keys for miniclient mapping

### ISSUE THREAD

**Issue by jhartm2** [OpenSageTV/sagetv-miniclient#72]
Please add the following keymaps:

https://developer.android.com/reference/android/view/KeyEvent.html#KEYCODE_GUIDE
https://developer.android.com/reference/android/view/KeyEvent.html#KEYCODE_INFO

Plus any of the "F" keys if they are not already mapped.:

https://developer.android.com/reference/android/view/KeyEvent.html#KEYCODE_F1

etc

these are passed when using a harmony hub connected to a shield/mibox as a keyboard.

thx

/jer

**Comment by stuckless** [comment]
Fixed in 1.2.8
