### ISSUE TITLE
No video during playback of mp4/avc/ac-3 file..

### ISSUE THREAD

**Issue by mhassman** [OpenSageTV/sagetv-miniclient#76]
Hi,

I'm experiencing difficulty with the miniclient playing a specific encode: mp4/avc/ac-3. Audio plays, but video does not.

For some reason, the mini client always selects software decoder and ignores the multiple hardware avc decoders available. I've tried switching to ExoPlayer and also changed AllowNativeSoftwareDecoders (on/off) - no improvement. Miniclient debug file attached. The Android device is a non-rooted Samsung Galaxy S7 w/Android v7.

fyi.. the encode is created via sage's internal transcode feature. Here are the specific parameters from sage.properties file: 
transcoder/formats/H.264-480p-archive=f\=mp4;MCompressionDetails\=-coder 0 -flags +loop -cmp +chroma -partitions +parti8x8+parti4x4+partp8x8+partb8x8 -me_method umh -subq 8 -me_range 16 -g 250 -keyint_min 25 -sc_threshold 40 -i_qfactor 0.71 -b_strategy 2 -qcomp 0.6 -qmin 10 -qmax 51 -qdiff 4 -bf 0 -refs 1 -directpred 3 -trellis 1 -flags2 -wpred-dct8x8 -wpredp 0 -rc_lookahead 50 -level 42 -crf 23 -minrate 500000 -maxrate 2000000 -bufsize 5000000 -deinterlace -strict experimental;[bf\=vid;f\=h264;fps\=29.97;w\=854;h\=480;][bf\=aud;]

This encode works fine on sage desktop and hd300.

Any ideas on why playback is failing on miniclient?
Thnx!
:-)

Sample file: http://216.129.119.211/38878271-0.mp4

-----------------------
MediaInfo:

General
Complete name                            : 38878271-0.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 573 MiB
Duration                                 : 59 min 59 s
Overall bit rate                         : 1 336 kb/s
Encoded date                             : UTC 1970-01-01 00:00:00
Tagged date                              : UTC 1970-01-01 00:00:00
Writing application                      : Lavf52.73.0

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Baseline@L4.2
Format settings, CABAC                   : No
Format settings, RefFrames               : 1 frame
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 59 min 59 s
Bit rate                                 : 950 kb/s
Width                                    : 854 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 29.970 (29970/1000) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.077
Stream size                              : 407 MiB (71%)
Writing library                          : x264 core 104
Encoding settings                        : cabac=0 / ref=1 / deblock=1:0:0 / analyse=0x1:0x111 / me=umh / subme=8 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=0 / me_range=16 / chroma_me=1 / trellis=0 / 8x8dct=0 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=7 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / constrained_intra=0 / bframes=0 / weightp=0 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=50 / rc=crf / mbtree=1 / crf=23.0 / qcomp=0.60 / qpmin=10 / qpmax=51 / qpstep=4 / vbv_maxrate=2000 / vbv_bufsize=5000 / crf_max=0.0 / ip_ratio=1.41 / aq=1:1.00 / nal_hrd=none
Encoded date                             : UTC 1970-01-01 00:00:00
Tagged date                              : UTC 1970-01-01 00:00:00

Audio
ID                                       : 2
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Format settings, Endianness              : Big
Codec ID                                 : ac-3
Duration                                 : 59 min 59 s
Bit rate mode                            : Constant
Bit rate                                 : 384 kb/s
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 165 MiB (29%)
Language                                 : English
Service kind                             : Complete Main
Encoded date                             : UTC 1970-01-01 00:00:00
Tagged date                              : UTC 1970-01-01 00:00:00

--------------------------
[sagetv-miniclient.txt](https://github.com/OpenSageTV/sagetv-miniclient/files/1714649/sagetv-miniclient.txt)

**Comment by jvl711** [comment]
@mhassman

Can you confirm this is still an issue.  If it is I will reopen the ticket.

Josh
