### ISSUE TITLE
Scishion v88 4k android 6.0 No Video in recording playback

### ISSUE THREAD

**Issue by trobinson03195** [OpenSageTV/sagetv-miniclient#85]
The above TV box shows a black screen during play back of 1080 recordings. Recordings @ 576 play back fine. Playing with decoders doesn't change anything. I turned on loging but can't find a log or were the app installed.

Mini client 1.3.2

CPU: Rockchip 3229 Quad-Core(1.5GHZ)
RAM: DDRIII 1 GB
ROME: 8GB eMMC
SD: 32GB
OS: Android 6.0
Ethernet: 100 m
WiFi:  802.11 b/g/n
Video Decode: H.265, VP9

Regards
Tim Robinson

**Comment by jvl711** [comment]
@trobinson03195 

Can you confirm if this is still an issue.  If it is I will reopen.

Josh
