### ISSUE TITLE
Seeking unresponsive, unable to fastforward/rewind

### ISSUE THREAD

**Issue by DarkWolf7** [OpenSageTV/sagetv-miniclient#87]
I have this issue regardless of which player I use, but I've been having it ever since version 1.3.1 (or somewhere around there). There are various issues I'm having with seeking:
* at the beginning of a recording, sometimes the recording will get stuck in a loop in the first two seconds and I can't escape it unless I fast forward. Rewinding to the same spot will cause it to happen again. ONLY happens at the beginning of a recording.
* sometimes when trying to fast forward (I use the 10 second skip forward), the SageTV won't 'let' me do so, the timeline will show that it jumps forward the 10 seconds, but it will snap back to where it was. Only way around it seems to be to mash the FF button until it gets 'unstuck'
*If paused, rewinding or fast forwarding seems to cause the timeline to seek a full 10-15 minutes forward. If near the end of a recording, this will cause Sage to trigger the end of the recording and return to the menu button.

I haven't been able to figure out any pattern to this, it seems to occur only sometimes, with some recordings, but the source or format of the recording doesn't seem to matter. I have an hdhomerun as well as a hauppauge tuner that records off the cable box, so I have both mpeg-ts recordings and whatever comes off the hdhomerun.

**Comment by stuckless** [comment]
Could you try the "PULL" Streaming mode from the App Setting?

**Comment by DarkWolf7** [comment]
That seems to have fixed it. It's a bit less responsive, but that's a small price to pay.

**Comment by jvl711** [comment]
This issue should hopefully be fixed in v1.6.3.  There are a number of fixes and enhancements for seeking.

Josh
