### ISSUE TITLE
Certain keyboard keys do not register in the miniclient

### ISSUE THREAD

**Issue by way-lo** [OpenSageTV/sagetv-miniclient#88]
There are a few keys on my Logitech K400 keyboard that do not register in the miniclient.  The 'show unmapped keypresses' option reveals:

Delete key = 'forward_del'
Insert key = 'insert'

**Comment by stuckless** [comment]
What should these keys do, by default?

**Comment by way-lo** [comment]
Delete should initiate the delete command.  I believe that's the normally assigned function in the server versions.  It's just not registering as a key that 'exists' in the miniclient from this keyboard.

I don't believe insert has a default function, but I've assigned to Guide.

**Comment by stuckless** [comment]
This will be in 1.4.2 release, but, I can't test it :(
