### ISSUE TITLE
Frame Advance & Slow Motion Advance

### ISSUE THREAD

**Issue by mwhittaker1024** [OpenSageTV/sagetv-miniclient#91]
On the HD300, you pause the video and then keep pressing the Pause button to advance a frame at a time. If you hold down the pause button it gives you a slow motion advance. Please add this funcitonality to the SageTV-miniclient if possible.

**Comment by jvl711** [comment]
@mwhittaker1024 

I did some initial investigation into this, and I was a little surprised, but it seems that SageTV might be causing the behavior we are seeing today. and not the Android Client.  It seems that when the playback is "Paused", and the client tells SageTV to "Pause" again, it appears that SageTV responds back to "Play".  I was a bit surprised by this.  I am not sure if the frame advance is baked into the HD300, or if there is some hidden method to tell sage to modify this behavior.

I think I may be able to create some special logic in the client to handle this.  In the event that the player state is paused, and another pause is requested, I could just advance a frame.  This seems doable.  I am going to attempt this for 1.7.0.  I am going to add it to the milestone for now.  No guarantees though.

Josh

**Comment by jvl711** [comment]
I was able to get this to work in ExoPlayer by handling subsequent pause commands on the client side.  It seems to be working pretty well.  The only issue I am currently having is that I have not be able to get the framerate of the video from ExoPlayer.  So I am assuming 30fps.  It works fairly well.  It also is only going to work for videos that the player supports natively.  It will not work if the transcoding is in use.

I am going to see if I can make the same update to the IJKPlayer implementation.

Josh

**Comment by mwhittaker1024** [comment]
Josh,

Thanks for the update. Any luck on getting the slow motion advance to work?

Mark
